[versions]
android-compileSdk = "36"
android-minSdk = "21"
androidx-activityCompose = "1.10.1"
androidx-ui-tooling = "1.7.8"
androidx-viewmodel = "2.10.0"
agp = "8.13.0"
koin = "4.1.0"
kotlin = "2.2.20"
materialIconsCore = "1.7.3"
navigationCompose = "2.9.0-beta03"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-ui-tooling" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }